name: depth_cov
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.1.55
  - cuda-documentation=12.1.55
  - cuda-driver-dev=11.7.99
  - cuda-gdb=12.1.55
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.55
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.1.55
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.1.55
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.1.55
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.1.55
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.12.1
  - fsspec=2023.3.0
  - gds-tools=1.6.0.25
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcufile=1.6.0.25
  - libcufile-dev=1.6.0.25
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lightning-utilities=0.7.0
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - nsight-compute=2023.1.0.15
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.0
  - pillow=9.4.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.15
  - python_abi=3.8
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-lightning=1.9.4
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - torchmetrics=0.11.3
  - torchvision=0.14.1
  - tqdm=4.65.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - addict==2.4.0
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - click==8.1.3
    - comm==0.1.2
    - configargparse==1.5.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - dash==2.8.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - flask==2.2.3
    - fonttools==4.39.0
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipywidgets==8.0.4
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-client==8.0.3
    - jupyter-core==5.2.0
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - nbformat==5.5.0
    - nest-asyncio==1.5.6
    - open3d==0.16.0
    - opencv-python==4.7.0.72
    - pandas==1.5.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.1.0
    - plotly==5.13.1
    - prompt-toolkit==3.0.38
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrealsense2==2.53.1.4623
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pyzmq==25.0.0
    - scikit-learn==1.2.1
    - scipy==1.10.1
    - stack-data==0.6.2
    - tenacity==8.2.2
    - threadpoolctl==3.1.0
    - tornado==6.2
    - traitlets==5.9.0
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.5
    - zipp==3.15.0