name: Open3D visualization config

device: cpu
dtype: float

# Divide by scale, then clamped to [min, max]
depth_scale: 1.0
depth_min: 0.0
depth_max: 5.0

# Scale of median depth for visualizing frustums, camera view
frustum_const: 0.01

follow_traj: True

pcd_shader: "defaultUnlit" # "defaultLit", "normals", "depth", "defaultUnlit"

gt_color: [0., 0., 0.]
tracking_color: [1.0, 0.0, 0.0]
kf_color: [0.0, 0.0, 1.0]
one_way_color: [0.0, 0.0, 0.1]

inducing_point_radius: 1
inducing_point_color: [1.0, 0.0, 0.0]